services:
  - type: web
    name: mcgfinances-api
    env: docker
    dockerfilePath: apps/api/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
  - type: web
    name: mcgfinances-web
    env: docker
    dockerfilePath: apps/web/Dockerfile
    plan: free
    autoDeploy: true
  - type: worker
    name: mcgfinances-worker
    env: docker
    dockerfilePath: apps/worker/Dockerfile
    plan: free
    autoDeploy: true
  - type: redis
    name: mcgfinances-redis
    plan: free
  - type: postgres
    name: mcgfinances-db
    plan: free
